// <auto-generated />
using System;
using Mariia_S_301052981.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mariia_S_301052981.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mariia_S_301052981.Models.Club", b =>
                {
                    b.Property<string>("ClubFullName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Ground");

                    b.Property<string>("HeadCoachName");

                    b.HasKey("ClubFullName");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Mariia_S_301052981.Models.Player", b =>
                {
                    b.Property<string>("PlayerName")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Age");

                    b.Property<string>("ClubFullName");

                    b.Property<string>("CountryOfBirth");

                    b.Property<string>("PlayingPosition");

                    b.HasKey("PlayerName");

                    b.HasIndex("ClubFullName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Mariia_S_301052981.Models.Player", b =>
                {
                    b.HasOne("Mariia_S_301052981.Models.Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubFullName");
                });
#pragma warning restore 612, 618
        }
    }
}
